import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import CenterLayout from '../components/center-layout'
import StackLayout from '../components/stack-layout'
import BoxLayout from '../components/box-layout'
import FeaturedImage from '../components/featured-image'
import theme from '../config/theme'

const cards = [
  { siteName: 'siliconjungle.io', title: 'Social platforms and analysis tools', description: 'Focusing on fostering healthy relationships and communities', src: '/danger-of-likes.png', href: 'https://www.siliconjungle.io' },
  { siteName: 'siliconjungle.io', title: 'Social platforms and analysis tools', description: 'Focusing on fostering healthy relationships and communities', src: '/danger-of-likes.png', href: 'https://www.siliconjungle.io' },
  { siteName: 'siliconjungle.io', title: 'Social platforms and analysis tools', description: 'Focusing on fostering healthy relationships and communities', src: '/danger-of-likes.png', href: 'https://www.siliconjungle.io' },
  { siteName: 'siliconjungle.io', title: 'Social platforms and analysis tools', description: 'Focusing on fostering healthy relationships and communities', src: '/danger-of-likes.png', href: 'https://www.siliconjungle.io' },
]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CenterLayout>
        <StackLayout spacing={theme.spacing.m}>
          {cards.map(({ siteName, title, description, src, href }, i) => (
            <BoxLayout hasPadding hasShadow key={i}>
              <Link href={href}>
                <a target="_blank">
                  <BoxLayout backgroundColor={theme.color.grey}>
                    <FeaturedImage src={src} alt={title} />
                    <BoxLayout hasPadding>
                      <StackLayout>
                        <BoxLayout>
                          <span>{siteName}</span>
                        </BoxLayout>
                        <BoxLayout>
                          <span>{title}</span>
                        </BoxLayout>
                        <BoxLayout>
                          <span>{description}</span>
                        </BoxLayout>
                      </StackLayout>
                    </BoxLayout>
                  </BoxLayout>
                </a>
              </Link>
            </BoxLayout>
          ))}
        </StackLayout>
      </CenterLayout>
    </div>
  )
}
